"""
RCL (Renewable Component Library): catalog search and file download functions.

Generated by generate_sdk_python.py. Do not edit. The filter keywords,
field names, and enum values come from the RCL OpenAPI spec.

Provides access to PV module (PAN) and inverter (OND) files hosted in the
DNV Renewable Component Library, using the same ``SF_API_KEY`` as the main
SolarFarmer API.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, TypedDict

from typing_extensions import Unpack

from ..api import RCLClient, SolarFarmerAPIError, _parse_error_body, map_http_error_to_message
from ..logging import get_logger
from ._generated import (
    FIELD_MAP,
    InverterField,
    InverterFilters,
    ModuleField,
    ModuleFilters,
    RCLInverterItemDict,
    RCLModuleItemDict,
)

if TYPE_CHECKING:
    # Only needed for type hints. The runtime import of requests stays in api.py.
    import requests

_logger = get_logger(__name__)

__all__ = [
    "RCLRateLimitInfo",
    "RCLInverterItemDict",
    "RCLModuleItemDict",
    "RCLInverterCatalogResponse",
    "RCLModuleCatalogResponse",
    "list_inverters",
    "list_modules",
    "download_file",
    "get_rate_limit_status",
]


@dataclass
class RCLRateLimitInfo:
    """Rate limit information parsed from RCL API response headers.

    Attributes
    ----------
    remaining : int
        Number of downloads remaining in the current period.
    limit : int
        Total download allowance for the current period.
    reset_timestamp : int
        Unix timestamp when the quota resets.
    """

    remaining: int
    limit: int
    reset_timestamp: int

    @property
    def reset_datetime(self) -> datetime:
        """Reset time as a UTC-aware datetime."""
        return datetime.fromtimestamp(self.reset_timestamp, tz=timezone.utc)

    @property
    def usage_percent(self) -> float:
        """Percentage of the limit already consumed."""
        if self.limit == 0:
            return 100.0
        return ((self.limit - self.remaining) / self.limit) * 100

    def __str__(self) -> str:
        return f"{self.remaining}/{self.limit} downloads remaining (resets {self.reset_datetime})"


class _RCLCatalogResponseBase(TypedDict):
    """Shared keys for paginated RCL catalog responses."""

    total: int
    skip: int
    take: int
    rate_limit: RCLRateLimitInfo | None


class RCLInverterCatalogResponse(_RCLCatalogResponseBase):
    """Paginated response from ``list_inverters()``."""

    items: list[RCLInverterItemDict]


class RCLModuleCatalogResponse(_RCLCatalogResponseBase):
    """Paginated response from ``list_modules()``."""

    items: list[RCLModuleItemDict]


def _extract_rate_limit(response: requests.Response) -> RCLRateLimitInfo:
    """Parse rate limit headers from an RCL response and log the current quota.

    Raises
    ------
    SolarFarmerAPIError
        If any rate-limit header is missing or cannot be parsed as an integer.
    """
    required_headers = ("X-RateLimit-Remaining", "X-RateLimit-Limit", "X-RateLimit-Reset")
    missing = [h for h in required_headers if h not in response.headers]
    if missing:
        raise SolarFarmerAPIError(
            response.status_code,
            f"RCL response is missing rate-limit header(s): {', '.join(missing)}",
        )

    try:
        info = RCLRateLimitInfo(
            remaining=int(response.headers["X-RateLimit-Remaining"]),
            limit=int(response.headers["X-RateLimit-Limit"]),
            reset_timestamp=int(response.headers["X-RateLimit-Reset"]),
        )
    except (TypeError, ValueError) as err:
        raise SolarFarmerAPIError(
            response.status_code,
            f"RCL response has invalid rate-limit header value(s): {sorted(response.headers)}",
        ) from err

    _logger.info(
        "RCL download quota: %d remaining (%.1f%% used). Resets %s",
        info.remaining,
        info.usage_percent,
        info.reset_datetime,
    )
    return info


def _raise_for_status(response: requests.Response) -> None:
    """Raise a ``SolarFarmerAPIError`` carrying the API's own error message."""
    text = response.text
    message = map_http_error_to_message(response.status_code, text, _parse_error_body(text))
    try:
        problem_details_json = response.json()
    except Exception:
        problem_details_json = None
    raise SolarFarmerAPIError(response.status_code, message, problem_details_json)


_OPERATORS = {"contains", "fuzzy", "gt", "gte", "lt", "lte"}


def _build_query_params(
    take: int = 25,
    skip: int = 0,
    order_by: str | None = None,
    order_dir: str = "ASC",
    output_parameter: list[str] | None = None,
    **filters: object,
) -> dict:
    """Build a query-parameter dict for an RCL catalog request.

    Filter keywords use the ``field``, ``field_contains``, ``field_gte``
    pattern and convert to the dot-notation form the RCL API expects
    (e.g. ``filter.pNom.gte=400``).
    """
    params: dict = {"take": take, "skip": skip}

    if order_by:
        params["orderBy"] = order_by
        params["orderDir"] = order_dir

    if output_parameter:
        params["outputParameter"] = ",".join(output_parameter)

    for key, value in filters.items():
        if value is None:
            continue
        if "." in key:
            # Raw dot-notation key passed through **kwargs; use it unchanged.
            params[key] = value
            continue
        parts = key.rsplit("_", 1)
        if len(parts) == 2 and parts[1] in _OPERATORS:
            field, op = parts
            api_field = FIELD_MAP.get(field, field)
            params[f"filter.{api_field}.{op}"] = value
        else:
            api_field = FIELD_MAP.get(key, key)
            params[f"filter.{api_field}"] = value

    return params


def _catalog_request(endpoint: str, query_params: dict, api_key: str | None) -> dict:
    """Execute an RCL catalog GET request and return a response dict."""
    client = RCLClient()
    response = client.get(endpoint, params=query_params, api_key=api_key)

    if not response.ok:
        _raise_for_status(response)

    data = response.json()
    missing = [key for key in ("items", "total") if key not in data]
    if missing:
        raise SolarFarmerAPIError(
            response.status_code,
            f"RCL catalog response is missing key(s): {', '.join(missing)}",
        )

    try:
        rate_limit = _extract_rate_limit(response)
    except SolarFarmerAPIError as err:
        # Rate-limit metadata is secondary to the catalog data. Do not fail the
        # search over it, and do not hide the problem.
        _logger.warning("Could not read RCL rate-limit headers: %s", err)
        rate_limit = None

    return {
        "items": data["items"],
        "total": data["total"],
        "skip": data.get("skip", query_params.get("skip", 0)),
        "take": data.get("take", query_params.get("take", 25)),
        "rate_limit": rate_limit,
    }


def list_inverters(
    *,
    api_key: str | None = None,
    take: int = 25,
    skip: int = 0,
    order_by: InverterField | None = None,
    order_dir: str = "ASC",
    output_parameter: list[InverterField] | None = None,
    verbose: bool = True,
    **filters: Unpack[InverterFilters],
) -> RCLInverterCatalogResponse:
    """
    List published PV inverters

    Parameters
    ----------
    api_key : str, optional
        API token. Defaults to the ``SF_API_KEY`` environment variable.
    take : int
        Page size (maximum 10000). Default 25.
    skip : int
        Pagination offset. Default 0.
    order_by : InverterField, optional
        Field to sort by. Defaults to ``"manufacturer"`` server-side.
    order_dir : str
        Sort direction: ``"ASC"`` or ``"DESC"``. Default ``"ASC"``.
    output_parameter : list of InverterField, optional
        Fields to include in the response. Reduces payload size.
    verbose : bool
        If ``True`` (default), prints a one-line summary after the request.
    **filters : InverterFilters
        Filter keywords. Commonly used:

        - ``effic_max_gte``: Minimum peak efficiency as a **percentage** (0-100).
        - ``lifecycle_status``: Lifecycle status of the version this row reports.
        - ``manufacturer``: Exact manufacturer match (case-sensitive).
        - ``manufacturer_fuzzy``: Trigram similarity match on the manufacturer name: case-insensitive and typo-tolerant.
        - ``model_contains``: Substring search on the model name (case-sensitive).
        - ``model_fuzzy``: Trigram similarity match on the model name: case-insensitive and typo-tolerant.
        - ``nb_mppt_gte``: Minimum number of independent MPPT inputs.
        - ``p_nom_conv_gte``: AC nameplate power lower bound in **kW** (PVsyst OND convention).
        - ``p_nom_conv_lte``: AC nameplate power upper bound in **kW**.
        - ``v_abs_max_lte``: Maximum DC bus voltage ceiling (V).

        See :class:`~solarfarmer.rcl.InverterFilters` for every
        accepted keyword and its type.

    Returns
    -------
    RCLInverterCatalogResponse
        Dict with keys ``items`` (list of dicts with camelCase wire keys),
        ``total``, ``skip``, ``take``, ``rate_limit``.

    Raises
    ------
    SolarFarmerAPIError
        If the API returns a non-2xx response.
    ValueError
        If no API key is found.

    Examples
    --------
    >>> result = sf.rcl.list_inverters(
    ...     effic_max_gte=98,
    ...     lifecycle_status="deprecated",
    ... )
    >>> for item in result["items"]:
    ...     print(item["manufacturer"], item["model"])
    """
    params = _build_query_params(
        take=take,
        skip=skip,
        order_by=order_by,
        order_dir=order_dir,
        output_parameter=output_parameter,
        **filters,
    )
    result = _catalog_request("catalog/inverters", params, api_key)
    if verbose:
        print(f"INFO: {result['total']} inverters found, retrieved {len(result['items'])}.")
    return result  # type: ignore[return-value]


def list_modules(
    *,
    api_key: str | None = None,
    take: int = 25,
    skip: int = 0,
    order_by: ModuleField | None = None,
    order_dir: str = "ASC",
    output_parameter: list[ModuleField] | None = None,
    verbose: bool = True,
    **filters: Unpack[ModuleFilters],
) -> RCLModuleCatalogResponse:
    """
    List published PV modules

    Parameters
    ----------
    api_key : str, optional
        API token. Defaults to the ``SF_API_KEY`` environment variable.
    take : int
        Page size (maximum 10000). Default 25.
    skip : int
        Pagination offset. Default 0.
    order_by : ModuleField, optional
        Field to sort by. Defaults to ``"manufacturer"`` server-side.
    order_dir : str
        Sort direction: ``"ASC"`` or ``"DESC"``. Default ``"ASC"``.
    output_parameter : list of ModuleField, optional
        Fields to include in the response. Reduces payload size.
    verbose : bool
        If ``True`` (default), prints a one-line summary after the request.
    **filters : ModuleFilters
        Filter keywords. Commonly used:

        - ``bifaciality_factor_gte``: Minimum bifaciality factor (0.0 to 1.0).
        - ``lifecycle_status``: Lifecycle status of the version this row reports.
        - ``manufacturer``: Exact manufacturer match (case-sensitive).
        - ``manufacturer_fuzzy``: Trigram similarity match on the manufacturer name: case-insensitive and typo-tolerant.
        - ``model_contains``: Substring search on the model name (case-sensitive).
        - ``model_fuzzy``: Trigram similarity match on the model name: case-insensitive and typo-tolerant.
        - ``p_nom_gte``: Nameplate power lower bound in **W**.
        - ``p_nom_lte``: Nameplate power upper bound in **W**.
        - ``technol``: PVsyst cell technology code (case-sensitive).

        See :class:`~solarfarmer.rcl.ModuleFilters` for every
        accepted keyword and its type.

    Returns
    -------
    RCLModuleCatalogResponse
        Dict with keys ``items`` (list of dicts with camelCase wire keys),
        ``total``, ``skip``, ``take``, ``rate_limit``.

    Raises
    ------
    SolarFarmerAPIError
        If the API returns a non-2xx response.
    ValueError
        If no API key is found.

    Examples
    --------
    >>> result = sf.rcl.list_modules(
    ...     bifaciality_factor_gte=0.5,
    ...     lifecycle_status="deprecated",
    ... )
    >>> for item in result["items"]:
    ...     print(item["manufacturer"], item["model"])
    """
    params = _build_query_params(
        take=take,
        skip=skip,
        order_by=order_by,
        order_dir=order_dir,
        output_parameter=output_parameter,
        **filters,
    )
    result = _catalog_request("catalog/modules", params, api_key)
    if verbose:
        print(f"INFO: {result['total']} modules found, retrieved {len(result['items'])}.")
    return result  # type: ignore[return-value]


def download_file(
    file_uuid: str,
    filename: str,
    *,
    save_to_file: bool = True,
    directory_path: str | Path | None = None,
    file_path: str | Path | None = None,
    api_key: str | None = None,
) -> bytes:
    """
    Download a PAN or OND file from the Renewable Component Library.

    .. warning::
        Each call consumes one download against your monthly quota, even if
        the file was already downloaded before. Check
        :func:`get_rate_limit_status` before bulk downloads.

    Parameters
    ----------
    file_uuid : str
        The ``fileUuid`` value from a catalog query result item.
    filename : str
        Original filename (used when saving to a directory).
    save_to_file : bool
        Whether to write the content to disk. Default ``True``.
    directory_path : str or Path, optional
        Directory in which to save the file using ``filename``.
        Defaults to the current working directory when ``save_to_file=True``
        and ``file_path`` is not given.
    file_path : str or Path, optional
        Full destination path including filename. Overrides ``directory_path``.
    api_key : str, optional
        API token. Defaults to the ``SF_API_KEY`` environment variable.

    Returns
    -------
    bytes
        Raw file content, regardless of whether it was saved to disk.

    Raises
    ------
    SolarFarmerAPIError
        If the API returns a non-2xx response.
    ValueError
        If no API key is found, or ``filename`` is not a bare file name.
    """
    if file_path is not None:
        dest = Path(file_path)
    elif directory_path is not None or save_to_file:
        if not filename or "\\" in filename or Path(filename).name != filename:
            raise ValueError(
                f"filename must be a bare file name with no directory component, got {filename!r}"
            )
        base = Path(directory_path) if directory_path is not None else Path.cwd()
        dest = base / filename
    else:
        dest = None

    client = RCLClient()
    response = client.get(f"catalog/{file_uuid}", api_key=api_key)

    if not response.ok:
        _raise_for_status(response)

    content = response.content
    try:
        _extract_rate_limit(response)
    except SolarFarmerAPIError as err:
        # The file downloaded. Do not fail the download because the quota
        # headers could not be read.
        _logger.warning("Could not read RCL rate-limit headers: %s", err)

    if save_to_file and dest is not None:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(content)
        _logger.info("Saved RCL file to %s", dest)

    return content


def get_rate_limit_status(api_key: str | None = None) -> RCLRateLimitInfo:
    """
    Return current RCL rate limit status without consuming a download.

    Uses ``GET /catalog/modules?take=0``, which returns an empty page but
    includes the rate-limit headers.

    Raises
    ------
    SolarFarmerAPIError
        If the API returns a non-2xx response or rate limit headers are missing.
    ValueError
        If no API key is found.
    """
    client = RCLClient()
    response = client.get("catalog/modules", params={"take": 0}, api_key=api_key)

    if not response.ok:
        _raise_for_status(response)

    return _extract_rate_limit(response)
