"""RCL catalog wire types. Generated by generate_sdk_python.py. Do not edit."""

from __future__ import annotations

from typing import Literal, TypedDict


class RCLInverterItemDict(TypedDict, total=False):
    """One inverter row from ``GET /catalog/inverters``."""

    acSwitch: str
    compPMax: str
    compVMax: str
    componentId: str
    dataSource: str
    dcSwitch: str
    depth: float
    efficEuro: float
    efficMax: float
    fResNorm: float
    fileUuid: str
    filename: str
    flags: str
    hasDefaultPThresh: int
    height: float
    iDcMax: float
    iMaxAc: float
    iMaxDc: float
    iNomAc: float
    isolSurvey: str
    lifecycleStatus: Literal["draft", "under_review", "validated", "published", "deprecated", "archived"]
    lifecycleStatusDate: str
    manufacturer: str
    masterSlave: str
    modeAff: int
    modeAffEnum: str
    modeOper: str
    model: str
    monoTri: str
    msThresh: float
    nbInputs: int
    nbMppt: int
    nbMsInterne: int
    nightLoss: float
    pInEffMax: float
    pLim1: float
    pLimAbs: float
    pMaxDc: float
    pMaxOut: float
    pNomConv: float
    pSeuil: float
    pThreshEff: float
    tanPhiMax: float
    tanPhiMin: float
    tpLim1: float
    tpLimAbs: float
    tpMax: float
    tpNom: float
    transfo: str
    unitAff: int
    unitAffEnum: str
    vAbsMax: int
    vMppMax: int
    vMppMin: int
    vMppNom: float
    vMppPMax: float
    vOutConv: float
    version: str
    weight: float
    width: float


class InverterFilters(TypedDict, total=False):
    """Filter keywords accepted by the matching list call."""

    data_source: str
    data_source_contains: str
    depth: float
    depth_contains: str
    depth_gt: float
    depth_gte: float
    depth_lt: float
    depth_lte: float
    effic_euro: float
    effic_euro_contains: str
    effic_euro_gt: float
    effic_euro_gte: float
    effic_euro_lt: float
    effic_euro_lte: float
    effic_max: float
    effic_max_contains: str
    effic_max_gt: float
    effic_max_gte: float
    effic_max_lt: float
    effic_max_lte: float
    file_uuid: str
    file_uuid_contains: str
    filename: str
    filename_contains: str
    flags: str
    flags_contains: str
    height: float
    height_contains: str
    height_gt: float
    height_gte: float
    height_lt: float
    height_lte: float
    i_max_dc: float
    i_max_dc_contains: str
    i_max_dc_gt: float
    i_max_dc_gte: float
    i_max_dc_lt: float
    i_max_dc_lte: float
    lifecycle_status: Literal["draft", "under_review", "validated", "published", "deprecated", "archived"]
    lifecycle_status_contains: str
    lifecycle_status_date: str
    lifecycle_status_date_contains: str
    lifecycle_status_date_gt: str
    lifecycle_status_date_gte: str
    lifecycle_status_date_lt: str
    lifecycle_status_date_lte: str
    manufacturer: str
    manufacturer_contains: str
    manufacturer_fuzzy: str
    mode_oper: str
    mode_oper_contains: str
    model: str
    model_contains: str
    model_fuzzy: str
    nb_mppt: int
    nb_mppt_contains: str
    nb_mppt_gt: int
    nb_mppt_gte: int
    nb_mppt_lt: int
    nb_mppt_lte: int
    p_max_out: float
    p_max_out_contains: str
    p_max_out_gt: float
    p_max_out_gte: float
    p_max_out_lt: float
    p_max_out_lte: float
    p_nom_conv: float
    p_nom_conv_contains: str
    p_nom_conv_gt: float
    p_nom_conv_gte: float
    p_nom_conv_lt: float
    p_nom_conv_lte: float
    transfo: str
    transfo_contains: str
    v_abs_max: int
    v_abs_max_contains: str
    v_abs_max_gt: int
    v_abs_max_gte: int
    v_abs_max_lt: int
    v_abs_max_lte: int
    v_mpp_max: int
    v_mpp_max_contains: str
    v_mpp_max_gt: int
    v_mpp_max_gte: int
    v_mpp_max_lt: int
    v_mpp_max_lte: int
    v_mpp_min: int
    v_mpp_min_contains: str
    v_mpp_min_gt: int
    v_mpp_min_gte: int
    v_mpp_min_lt: int
    v_mpp_min_lte: int
    v_out_conv: float
    v_out_conv_contains: str
    v_out_conv_gt: float
    v_out_conv_gte: float
    v_out_conv_lt: float
    v_out_conv_lte: float
    weight: float
    weight_contains: str
    weight_gt: float
    weight_gte: float
    weight_lt: float
    weight_lte: float
    width: float
    width_contains: str
    width_gt: float
    width_gte: float
    width_lt: float
    width_lte: float


class RCLModuleItemDict(TypedDict, total=False):
    """One module row from ``GET /catalog/modules``."""

    aRev: float
    absorb: float
    airMassRef: float
    bRev: float
    bifacialityFactor: float
    cellArea: float
    componentId: str
    d2MuTau: float
    dataSource: str
    depth: float
    fileUuid: str
    filename: str
    flags: str
    frontSurface: str
    gRef: float
    gamma: float
    height: float
    imp: float
    isc: float
    lidLoss: float
    lifecycleStatus: Literal["draft", "under_review", "validated", "published", "deprecated", "archived"]
    lifecycleStatusDate: str
    manufacturer: str
    model: str
    muGamma: float
    muIsc: float
    muPmpReq: float
    muVocSpec: float
    nCelP: int
    nCelS: int
    nDiode: int
    pNom: float
    pNomTolLow: float
    pNomTolUp: float
    rDiode: float
    rSerie: float
    rShunt: float
    rp0: float
    rpExp: float
    sandiaAmCorr: float
    subModuleLayout: str
    tRef: float
    technol: str
    vMaxIec: int
    vMaxUl: int
    vRevDiode: float
    version: str
    vmp: float
    voc: float
    weight: float
    width: float


class ModuleFilters(TypedDict, total=False):
    """Filter keywords accepted by the matching list call."""

    bifaciality_factor: float
    bifaciality_factor_contains: str
    bifaciality_factor_gt: float
    bifaciality_factor_gte: float
    bifaciality_factor_lt: float
    bifaciality_factor_lte: float
    data_source: str
    data_source_contains: str
    depth: float
    depth_contains: str
    depth_gt: float
    depth_gte: float
    depth_lt: float
    depth_lte: float
    file_uuid: str
    file_uuid_contains: str
    filename: str
    filename_contains: str
    height: float
    height_contains: str
    height_gt: float
    height_gte: float
    height_lt: float
    height_lte: float
    imp: float
    imp_contains: str
    imp_gt: float
    imp_gte: float
    imp_lt: float
    imp_lte: float
    isc: float
    isc_contains: str
    isc_gt: float
    isc_gte: float
    isc_lt: float
    isc_lte: float
    lifecycle_status: Literal["draft", "under_review", "validated", "published", "deprecated", "archived"]
    lifecycle_status_contains: str
    lifecycle_status_date: str
    lifecycle_status_date_contains: str
    lifecycle_status_date_gt: str
    lifecycle_status_date_gte: str
    lifecycle_status_date_lt: str
    lifecycle_status_date_lte: str
    manufacturer: str
    manufacturer_contains: str
    manufacturer_fuzzy: str
    model: str
    model_contains: str
    model_fuzzy: str
    mu_pmp_req: float
    mu_pmp_req_contains: str
    mu_pmp_req_gt: float
    mu_pmp_req_gte: float
    mu_pmp_req_lt: float
    mu_pmp_req_lte: float
    n_cel_p: int
    n_cel_p_contains: str
    n_cel_p_gt: int
    n_cel_p_gte: int
    n_cel_p_lt: int
    n_cel_p_lte: int
    n_cel_s: int
    n_cel_s_contains: str
    n_cel_s_gt: int
    n_cel_s_gte: int
    n_cel_s_lt: int
    n_cel_s_lte: int
    p_nom: float
    p_nom_contains: str
    p_nom_gt: float
    p_nom_gte: float
    p_nom_lt: float
    p_nom_lte: float
    technol: str
    technol_contains: str
    vmp: float
    vmp_contains: str
    vmp_gt: float
    vmp_gte: float
    vmp_lt: float
    vmp_lte: float
    voc: float
    voc_contains: str
    voc_gt: float
    voc_gte: float
    voc_lt: float
    voc_lte: float
    weight: float
    weight_contains: str
    weight_gt: float
    weight_gte: float
    weight_lt: float
    weight_lte: float
    width: float
    width_contains: str
    width_gt: float
    width_gte: float
    width_lt: float
    width_lte: float


InverterField = Literal[
    "acSwitch",
    "compPMax",
    "compVMax",
    "componentId",
    "dataSource",
    "dcSwitch",
    "depth",
    "efficEuro",
    "efficMax",
    "fResNorm",
    "fileUuid",
    "filename",
    "flags",
    "hasDefaultPThresh",
    "height",
    "iDcMax",
    "iMaxAc",
    "iMaxDc",
    "iNomAc",
    "isolSurvey",
    "lifecycleStatus",
    "lifecycleStatusDate",
    "manufacturer",
    "masterSlave",
    "modeAff",
    "modeAffEnum",
    "modeOper",
    "model",
    "monoTri",
    "msThresh",
    "nbInputs",
    "nbMppt",
    "nbMsInterne",
    "nightLoss",
    "pInEffMax",
    "pLim1",
    "pLimAbs",
    "pMaxDc",
    "pMaxOut",
    "pNomConv",
    "pSeuil",
    "pThreshEff",
    "tanPhiMax",
    "tanPhiMin",
    "tpLim1",
    "tpLimAbs",
    "tpMax",
    "tpNom",
    "transfo",
    "unitAff",
    "unitAffEnum",
    "vAbsMax",
    "vMppMax",
    "vMppMin",
    "vMppNom",
    "vMppPMax",
    "vOutConv",
    "version",
    "weight",
    "width",
]


ModuleField = Literal[
    "aRev",
    "absorb",
    "airMassRef",
    "bRev",
    "bifacialityFactor",
    "cellArea",
    "componentId",
    "d2MuTau",
    "dataSource",
    "depth",
    "fileUuid",
    "filename",
    "flags",
    "frontSurface",
    "gRef",
    "gamma",
    "height",
    "imp",
    "isc",
    "lidLoss",
    "lifecycleStatus",
    "lifecycleStatusDate",
    "manufacturer",
    "model",
    "muGamma",
    "muIsc",
    "muPmpReq",
    "muVocSpec",
    "nCelP",
    "nCelS",
    "nDiode",
    "pNom",
    "pNomTolLow",
    "pNomTolUp",
    "rDiode",
    "rSerie",
    "rShunt",
    "rp0",
    "rpExp",
    "sandiaAmCorr",
    "subModuleLayout",
    "tRef",
    "technol",
    "vMaxIec",
    "vMaxUl",
    "vRevDiode",
    "version",
    "vmp",
    "voc",
    "weight",
    "width",
]


FIELD_MAP: dict[str, str] = {
    "bifaciality_factor": "bifacialityFactor",
    "data_source": "dataSource",
    "effic_euro": "efficEuro",
    "effic_max": "efficMax",
    "file_uuid": "fileUuid",
    "i_max_dc": "iMaxDc",
    "lifecycle_status": "lifecycleStatus",
    "lifecycle_status_date": "lifecycleStatusDate",
    "mode_oper": "modeOper",
    "mu_pmp_req": "muPmpReq",
    "n_cel_p": "nCelP",
    "n_cel_s": "nCelS",
    "nb_mppt": "nbMppt",
    "p_max_out": "pMaxOut",
    "p_nom": "pNom",
    "p_nom_conv": "pNomConv",
    "v_abs_max": "vAbsMax",
    "v_mpp_max": "vMppMax",
    "v_mpp_min": "vMppMin",
    "v_out_conv": "vOutConv",
}
